(require-package 'helm)
;;(require-package 'helm-org-rifle)
;;(require-package 'helm-ag)
;;(global-set-key (kbd "C-s") 'helm-org-rifle-current-buffer)
;;(global-set-key (kbd "C-x C-a") 'helm-org-rifle)
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x C-m") 'helm-M-x)
(global-set-key (kbd "M-y") 'helm-show-kill-ring)
(global-set-key (kbd "C-x b") 'helm-mini)
(global-set-key (kbd "C-x C-b") 'helm-buffers-list)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-h f") 'helm-apropos)
(global-set-key (kbd "C-h r") 'helm-info-emacs)
(global-set-key (kbd "C-h C-l") 'helm-locate-library)
(global-set-key (kbd "C-s") 'helm-occur)

(helm-mode 1)
(setq helm-ff-auto-update-initial-value t)
(provide 'init-helm)
